name: Branch Protection & Deployment Checks

on:
  pull_request:
    branches: [main, staging]
  push:
    branches: [main, staging]

jobs:
  # Branch Protection voor main
  protect-main:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Verify staging merge
        run: |
          # Controleer of de PR van staging naar main komt
          if [ "${{ github.head_ref }}" != "staging" ]; then
            echo "❌ Directe merges naar main zijn niet toegestaan. Gebruik staging als tussenstap."
            exit 1
          fi
          echo "✅ Merge van staging naar main is toegestaan"

  # Staging deployment checks
  staging-checks:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test || echo "⚠️ Geen tests gevonden - voeg tests toe voor betere kwaliteit"
        
      - name: Build check
        run: npm run build
        
      - name: Lint check
        run: npm run lint || echo "⚠️ Geen linting gevonden - voeg ESLint toe voor code kwaliteit"

  # Production deployment checks (alleen via staging)
  production-checks:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Verify staging deployment
        run: |
          echo "✅ Production deployment wordt alleen uitgevoerd na succesvolle staging merge"
          echo "🔍 Controleer staging deployment op: https://staging.undsovrd.vercel.app" 